structure(list(method = "PUT", url = "sbapi/files/hash/data2.csv", 
    status_code = 201L, headers = structure(list(server = "nginx/1.24.0", 
        date = "Tue, 05 Dec 2023 14:51:44 GMT", `content-type` = "application/json", 
        `content-length` = "655", `x-ratelimit-limit` = "1000", 
        `x-ratelimit-remaining` = "986", `x-ratelimit-reset` = "1701787965", 
        `retry-after` = "60", `permissions-policy` = "interest-cohort=()", 
        `x-frame-options` = "sameorigin", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `content-security-policy` = "default-src 'self' fonts.googleapis.com *.gstatic.com data: 'unsafe-inline' 'unsafe-eval' blob: zenodo-broker.web.cern.ch zenodo-broker-qa.web.cern.ch maxcdn.bootstrapcdn.com cdnjs.cloudflare.com ajax.googleapis.com webanalytics.web.cern.ch", 
        `strict-transport-security` = "max-age=31556926; includeSubDomains", 
        `referrer-policy` = "strict-origin-when-cross-origin", 
        `set-cookie` = "csrftoken=eyJhbGciOiJIUzUxMiIsImlhdCI6MTcwMTc4NzkwNCwiZXhwIjoxNzAxODc0MzA0fQ.IndkNmFtVXJtUDRBUHE4UGtMTTFBcEg4cFNTSnk5TWp4Ig.qTWh_AQuI7laneu7frJaRUJOYxmZrVGjMFUEYqkBL_GI4mty1agd4Crl7aJBL14462vYI0SqYW8VySPzJzuE6w; Expires=Tue, 12 Dec 2023 14:51:44 GMT; Max-Age=604800; Secure; Path=/; SameSite=Lax", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset", 
        `strict-transport-security` = "max-age=15768000", `x-request-id` = "053832b65549d76f754d70d0b9b1d364", 
        `set-cookie` = "04f20c86f07421a9ec0f9d5ba4be544f=7705ef0ecdb4f5b5c6800bf05b654082; path=/; HttpOnly; Secure; SameSite=None"), class = "httr2_headers"), 
    body = charToRaw("{\"created\": \"2022-01-01T00:00:00+00:00\", \"updated\": \"2022-01-01T00:00:00+00:00\", \"version_id\": \"6ad92a1b-6adb-4da8-8049-3eacb50ccdc2\", \"key\": \"data2.csv\", \"size\": 625, \"mimetype\": \"text/csv\", \"checksum\": \"md5:cc624d72ede85ef061afa494d9951f6f\", \"is_head\": true, \"delete_marker\": false, \"links\": {\"self\": \"sbapi/files/hash/data2.csv\", \"version\": \"sbapi/files/hash/data2.csv?versionId=6ad92a1b-6adb-4da8-8049-3eacb50ccdc2\", \"uploads\": \"sbapi/files/hash/data2.csv?uploads\"}}"), 
    request = structure(list(url = "https://sandbox.zenodo.org/api/files/1565343c-0039-4c00-a989-6aa546bbea9e/data2.csv", 
        method = "PUT", headers = list(Authorization = "Bearer 5BhlwRXYBj8LlyEiQtmYqeRklDjdMIKTsJM0jLN9UL8oWPFCbd7glEUpjBHz", 
            `Content-Type` = "application/octet-stream"), body = list(
            data = structure("/tmp/RtmpJvdhOm/data2.csv", class = "httr2_path"), 
            type = "raw-file", content_type = "", params = list()), 
        fields = list(), options = list(), policies = list()), class = "httr2_request"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
