structure(list(method = "POST", url = "sbapi/deposit/depositions", 
    status_code = 201L, headers = structure(list(server = "nginx/1.24.0", 
        date = "Mon, 19 Feb 2024 12:21:56 GMT", `content-type` = "application/json", 
        `content-length` = "2033", etag = "\"5\"", `x-ratelimit-limit` = "1000", 
        `x-ratelimit-remaining` = "999", `x-ratelimit-reset` = "1708345377", 
        `retry-after` = "60", `permissions-policy` = "interest-cohort=()", 
        `x-frame-options` = "sameorigin", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `content-security-policy` = "default-src 'self' fonts.googleapis.com *.gstatic.com data: 'unsafe-inline' 'unsafe-eval' blob: zenodo-broker.web.cern.ch zenodo-broker-qa.web.cern.ch maxcdn.bootstrapcdn.com cdnjs.cloudflare.com ajax.googleapis.com webanalytics.web.cern.ch", 
        `strict-transport-security` = "max-age=31556926; includeSubDomains", 
        `referrer-policy` = "strict-origin-when-cross-origin", 
        `set-cookie` = "csrftoken=eyJhbGciOiJIUzUxMiIsImlhdCI6MTcwODM0NTMxNiwiZXhwIjoxNzA4NDMxNzE2fQ.IjloYkwzQU9ySEFXbUk0NWpFdHlpZVIwcGNSa0ZuY2tFIg.oErpVyZwqc1yllLPkQsajOjJk84klrc7NyBHc1LGtNwXZfDX1Va-I1PJOfJiv4LUIILjPQHu9Ym3aNRp0eJW_A; Expires=Mon, 26 Feb 2024 12:21:56 GMT; Max-Age=604800; Secure; Path=/; SameSite=Lax", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset", 
        `strict-transport-security` = "max-age=15768000", `x-request-id` = "1772aefc75a2cad800971bb0c551487d", 
        `set-cookie` = "04f20c86f07421a9ec0f9d5ba4be544f=7705ef0ecdb4f5b5c6800bf05b654082; path=/; HttpOnly; Secure; SameSite=None"), class = "httr2_headers"), 
    body = charToRaw("{\"created\": \"2022-01-01T00:00:00+00:00\", \"modified\": \"2022-01-01T00:00:00+00:00\", \"id\": 29712, \"conceptrecid\": \"29711\", \"metadata\": {\"title\": \"New Title\", \"publication_date\": \"2022-01-01\", \"description\": \"## abstract\\\\n\\\\nThis is the abstract\\\\n\\\\n## description\\nThis is the description\\n\\n## version\\n1.0\", \"access_right\": \"restricted\", \"creators\": [{\"name\": \"A. Person\", \"affiliation\": null}, {\"name\": \"B. Person\", \"affiliation\": null}], \"keywords\": [\"one\", \"two\", \"three\"], \"imprint_publisher\": \"Zenodo\", \"notes\": \"\\\\n\\\\n---start-deposits-meta---\\\\n{\\\"abstract\\\":\\\"This is the abstract\\\",\\\"accessRights\\\":\\\"closed\\\",\\\"creator\\\":[{\\\"name\\\":\\\"A. Person\\\"},{\\\"name\\\":\\\"B. Person\\\"}],\\\"description\\\":\\\"## description\\\\nThis is the description\\\\n\\\\n## version\\\\n1.0\\\",\\\"subject\\\":\\\"## keywords\\\\none, two\\\\nthree\\\",\\\"title\\\":\\\"New Title\\\"}\\\\n---end-deposits-meta---\\\\n\", \"upload_type\": \"other\", \"prereserve_doi\": {\"doi\": \"10.5281/zenodo.29712\", \"recid\": 29712}}, \"title\": \"New Title\", \"links\": {\"self\": \"sbapi/deposit/depositions/29712\", \"html\": \"https://sandbox.zenodo.org/deposit/29712\", \"badge\": \"https://sandbox.zenodo.org/badge/doi/.svg\", \"files\": \"sbapi/deposit/depositions/29712/files\", \"bucket\": \"sbapi/files/a49586e0-347d-4e85-b63b-f6b87d3df1c1\", \"latest_draft\": \"sbapi/deposit/depositions/29712\", \"latest_draft_html\": \"https://sandbox.zenodo.org/deposit/29712\", \"publish\": \"sbapi/deposit/depositions/29712/actions/publish\", \"edit\": \"sbapi/deposit/depositions/29712/actions/edit\", \"discard\": \"sbapi/deposit/depositions/29712/actions/discard\", \"newversion\": \"sbapi/deposit/depositions/29712/actions/newversion\", \"registerconceptdoi\": \"sbapi/deposit/depositions/29712/actions/registerconceptdoi\"}, \"record_id\": 29712, \"owner\": 623, \"files\": [], \"state\": \"unsubmitted\", \"submitted\": false}"), 
    request = structure(list(url = "https://sandbox.zenodo.org/api/deposit/depositions", 
        method = "POST", headers = structure(list(Authorization = "Bearer 5BhlwRXYBj8LlyEiQtmYqeRklDjdMIKTsJM0jLN9UL8oWPFCbd7glEUpjBHz"), redact = character(0)), 
        body = list(data = list(metadata = list(access_right = "closed", 
            creators = list(list(name = "A. Person"), list(name = "B. Person")), 
            title = "New Title", keywords = list("one", "two", 
                "three"), description = "## abstract\\n\\nThis is the abstract\\n\\n## description\nThis is the description\n\n## version\n1.0", 
            upload_type = "other", publication_date = "2022-01-01", 
            prereserve_doi = TRUE, notes = "\\n\\n---start-deposits-meta---\\n{\"abstract\":\"This is the abstract\",\"accessRights\":\"closed\",\"creator\":[{\"name\":\"A. Person\"},{\"name\":\"B. Person\"}],\"description\":\"## description\\nThis is the description\\n\\n## version\\n1.0\",\"subject\":\"## keywords\\none, two\\nthree\",\"title\":\"New Title\"}\\n---end-deposits-meta---\\n")), 
            type = "json", content_type = "application/json", 
            params = list(auto_unbox = TRUE, digits = 22, null = "null")), 
        fields = list(), options = list(), policies = list()), class = "httr2_request"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
