structure(list(method = "PUT", url = "sbapi/files/hash/data.csv", 
    status_code = 201L, headers = structure(list(server = "nginx/1.24.0", 
        date = "Mon, 19 Feb 2024 12:22:07 GMT", `content-type` = "application/json", 
        `content-length` = "651", `x-ratelimit-limit` = "1000", 
        `x-ratelimit-remaining` = "993", `x-ratelimit-reset` = "1708345388", 
        `retry-after` = "60", `permissions-policy` = "interest-cohort=()", 
        `x-frame-options` = "sameorigin", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `content-security-policy` = "default-src 'self' fonts.googleapis.com *.gstatic.com data: 'unsafe-inline' 'unsafe-eval' blob: zenodo-broker.web.cern.ch zenodo-broker-qa.web.cern.ch maxcdn.bootstrapcdn.com cdnjs.cloudflare.com ajax.googleapis.com webanalytics.web.cern.ch", 
        `strict-transport-security` = "max-age=31556926; includeSubDomains", 
        `referrer-policy` = "strict-origin-when-cross-origin", 
        `set-cookie` = "csrftoken=eyJhbGciOiJIUzUxMiIsImlhdCI6MTcwODM0NTMyNywiZXhwIjoxNzA4NDMxNzI3fQ.IlB6bUlwd3ZjZnlnMjNjM3FCeDVzU05GR2NHSVhFOUJDIg.gFA26HUlTxT29BzXvJd8-AasLk2UtvI6_pmJ8D5jO2dQLzXRAPFJh0Z8OG2MZWra_MxBzfEgOLPWfitWZwZykA; Expires=Mon, 26 Feb 2024 12:22:07 GMT; Max-Age=604800; Secure; Path=/; SameSite=Lax", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset", 
        `strict-transport-security` = "max-age=15768000", `x-request-id` = "2f46c8f030b0bc58ae1a71ed94492be3", 
        `set-cookie` = "04f20c86f07421a9ec0f9d5ba4be544f=7705ef0ecdb4f5b5c6800bf05b654082; path=/; HttpOnly; Secure; SameSite=None"), class = "httr2_headers"), 
    body = charToRaw("{\"created\": \"2022-01-01T00:00:00+00:00\", \"updated\": \"2022-01-01T00:00:00+00:00\", \"version_id\": \"39f591be-11aa-4ada-88af-81bf3a702d7d\", \"key\": \"data.csv\", \"size\": 625, \"mimetype\": \"text/csv\", \"checksum\": \"md5:cc624d72ede85ef061afa494d9951f6f\", \"is_head\": true, \"delete_marker\": false, \"links\": {\"self\": \"sbapi/files/hash/data.csv\", \"version\": \"sbapi/files/hash/data.csv?versionId=39f591be-11aa-4ada-88af-81bf3a702d7d\", \"uploads\": \"sbapi/files/hash/data.csv?uploads\"}}"), 
    request = structure(list(url = "https://sandbox.zenodo.org/api/files/a49586e0-347d-4e85-b63b-f6b87d3df1c1/data.csv", 
        method = "PUT", headers = list(Authorization = "Bearer 5BhlwRXYBj8LlyEiQtmYqeRklDjdMIKTsJM0jLN9UL8oWPFCbd7glEUpjBHz", 
            `Content-Type` = "application/octet-stream"), body = list(
            data = structure("/tmp/RtmpaWqqcJ/data.csv", class = "httr2_path"), 
            type = "raw-file", content_type = "", params = list()), 
        fields = list(), options = list(), policies = list()), class = "httr2_request"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
