structure(list(method = "PUT", url = "api/articles/30801242", 
    status_code = 205L, headers = structure(list(date = "Fri, 05 Dec 2025 13:38:31 GMT", 
        `content-type` = "application/json", `content-length` = "85", 
        location = "api/articles/30801242", server = "nginx", 
        `access-control-allow-origin` = "https://api.figshare.com", 
        `access-control-allow-methods` = "GET, POST, PUT, DELETE, OPTIONS", 
        `access-control-allow-headers` = "Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization", 
        `access-control-max-age` = "3600"), class = "httr2_headers"), 
    body = charToRaw("{\"location\": \"api/articles/30801242\", \"warnings\": []}"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 0.000113, 
    starttransfer = 0.164096, total = 0.16415), cache = new.env(parent = emptyenv())), class = "httr2_response")
