structure(list(method = "GET", url = "sbapi/files/hash/data.Rds", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 03 Jan 2023 09:45:30 GMT", `Content-Type` = "application/octet-stream", 
        `Content-Length` = "506", `Content-Disposition` = "attachment; filename=data.Rds", 
        `Accept-Ranges` = "none", `OC-Checksum` = "MD5:3ac485c9229cb2bd9f65bc0c3dfb2bb6", 
        `Accept-Ranges` = "bytes", `Content-Type` = "application/octet-stream", 
        `Content-MD5` = "3ac485c9229cb2bd9f65bc0c3dfb2bb6", `Content-Security-Policy` = "default-src 'none';", 
        `X-Content-Type-Options` = "nosniff", `X-Download-Options` = "noopen", 
        `X-Permitted-Cross-Domain-Policies` = "none", `X-Frame-Options` = "sameorigin", 
        `X-XSS-Protection` = "1; mode=block", `Last-Modified` = "Tue, 03 Jan 2023 09:45:29 GMT", 
        ETag = "\"md5:3ac485c9229cb2bd9f65bc0c3dfb2bb6\"", `X-RateLimit-Limit` = "100", 
        `X-RateLimit-Remaining` = "88", `X-RateLimit-Reset` = "1672739191", 
        `Retry-After` = "60", `Strict-Transport-Security` = "max-age=0", 
        `Referrer-Policy` = "strict-origin-when-cross-origin", 
        `Access-Control-Allow-Origin` = "*", `Access-Control-Expose-Headers` = "Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset", 
        `X-User-ID` = "115518"), class = "httr2_headers"), body = as.raw(c(0x4e, 
    0x41))), class = "httr2_response")
